---
- name: Check background jobs
  command: ghe-check-background-upgrade-jobs
  register: bg_jobs
  changed_when: false

- name: Verify all background jobs are complete
  assert:
    that:
      - "'Waiting for jobs' not in bg_jobs.stdout"
    fail_msg: "Background jobs are still running: {{ bg_jobs.stdout }}"
    success_msg: "All background jobs have completed successfully"

- name: Check queue status
  command: github-run-queue status
  register: queue_status
  changed_when: false

- name: Display queue status
  debug:
    var: queue_status.stdout_lines
