---
- name: Check basic system health
  command: ghe-health-check
  register: health_check
  changed_when: false

- name: Display health check results
  debug:
    var: health_check.stdout_lines

- name: Check GitHub services
  command: ghe-service-list --status
  register: service_status
  changed_when: false

- name: Display service status
  debug:
    var: service_status.stdout_lines

- name: Check replication status (if applicable)
  command: ghe-repl-status
  register: repl_status
  failed_when: false
  changed_when: false

- name: Display replication status (if applicable)
  debug:
    var: repl_status.stdout_lines
  when: repl_status.rc == 0

- name: Verify connectivity
  uri:
    url: "https://{{ ansible_host }}"
    validate_certs: no
    status_code: 200
  register: connectivity_check

- name: Display connectivity check result
  debug:
    msg: "GitHub Enterprise Server is accessible"
  when: connectivity_check.status == 200
