---
- name: Create download directory
  file:
    path: /tmp/ghes-upgrade
    state: directory
    mode: '0755'

- name: Download GitHub Enterprise upgrade package
  get_url:
    url: "{{ upgrade_pkg_url }}"
    dest: "/tmp/ghes-upgrade/github-enterprise-{{ target_version }}.pkg"
    checksum: "sha256:{{ upgrade_pkg_checksum }}"
    mode: '0644'
  register: download_result

- name: Display download result
  debug:
    msg: "Upgrade package downloaded to {{ download_result.dest }}"
