---
- name: Check if host is primary or replica
  command: ghe-repl-status
  register: repl_status
  failed_when: false
  changed_when: false

- name: Set node type based on replication status
  set_fact:
    is_primary: "{{ repl_status.rc != 0 or 'primary' in repl_status.stdout }}"
    is_replica: "{{ repl_status.rc == 0 and 'primary' not in repl_status.stdout }}"

- name: Download upgrade package
  include_tasks: download_package.yml
  when: is_primary | bool

- name: Upgrade primary node
  include_tasks: upgrade_primary.yml
  when: is_primary | bool
  tags: [upgrade_primary]

- name: Upgrade replica node
  include_tasks: upgrade_replica.yml
  when: is_replica | bool
  tags: [upgrade_replica]
