---
- name: Upgrade replica node
  command: "ghe-upgrade {{ download_result.dest }}"
  register: upgrade_result
  failed_when: upgrade_result.rc != 0

- name: Display upgrade result
  debug:
    var: upgrade_result.stdout_lines

- name: Start replication
  command: ghe-repl-start
  register: start_repl
  changed_when: "'Starting' in start_repl.stdout"

- name: Check replication status
  command: ghe-repl-status
  register: repl_status_after
  until: "'OK' in repl_status_after.stdout"
  retries: 12
  delay: 10
  changed_when: false

- name: Display replication status
  debug:
    var: repl_status_after.stdout_lines
