---
- name: Check if backup utilities are installed
  stat:
    path: "{{ backup_utils_install_dir }}/bin/ghe-backup"
  register: backup_bin
  delegate_to: "{{ item }}"
  with_items: "{{ groups['backup_server'] }}"

- name: Fail if backup utilities are not installed
  fail:
    msg: "GitHub Backup Utilities not found at {{ backup_utils_install_dir }}/bin/ghe-backup"
  when: not backup_bin.stat.exists
  delegate_to: "{{ item }}"
  with_items: "{{ groups['backup_server'] }}"

- name: Get current backup utilities version
  command: "{{ backup_utils_install_dir }}/bin/ghe-backup -v"
  register: backup_utils_version
  changed_when: false
  delegate_to: "{{ item }}"
  with_items: "{{ groups['backup_server'] }}"

- name: Display backup utilities version
  debug:
    msg: "GitHub Backup Utilities version: {{ backup_utils_version.stdout }}"
  delegate_to: "{{ item }}"
  with_items: "{{ groups['backup_server'] }}"

- name: Run GitHub Backup
  command: "{{ backup_utils_install_dir }}/bin/ghe-backup"
  register: backup_result
  changed_when: backup_result.rc == 0
  delegate_to: "{{ item }}"
  with_items: "{{ groups['backup_server'] }}"

- name: Display backup results
  debug:
    msg: "{{ backup_result.stdout_lines }}"
  delegate_to: "{{ item }}"
  with_items: "{{ groups['backup_server'] }}"
