apiVersion: v2
name: platform-prereqs
description: Shared platform prerequisites for application deployments
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - prerequisites
  - serviceaccount
  - csi
  - keyvault
  - storage
maintainers:
  - name: Platform Team
    email: platform@yourcompany.com
