---
# playbooks/deploy.yml
# Main deployment playbook

- name: Deploy Helm Application
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    # Default cloud provider (can be overridden via -e)
    cloud: azure
    # Default environment
    env: dev
    # Apps directory
    apps_dir: "{{ playbook_dir }}/../apps"
    # Deploy all apps flag
    deploy_all: false

  pre_tasks:
    - name: Validate required variables
      ansible.builtin.assert:
        that:
          - app is defined or deploy_all | bool
        fail_msg: "Either 'app' must be defined or 'deploy_all' must be true"
        success_msg: "Variables validated"

    - name: Get list of all apps
      ansible.builtin.find:
        paths: "{{ apps_dir }}"
        file_type: directory
      register: all_apps
      when: deploy_all | bool

    - name: Set apps to deploy
      ansible.builtin.set_fact:
        apps_to_deploy: >-
          {{
            all_apps.files | map(attribute='path') | map('basename') | list
            if deploy_all | bool
            else [app]
          }}

  tasks:
    - name: Deploy each application
      ansible.builtin.include_role:
        name: helm_deploy
      vars:
        app_name: "{{ current_app }}"
        app_config_path: "{{ apps_dir }}/{{ current_app }}"
        cloud_provider: "{{ cloud }}"
      loop: "{{ apps_to_deploy }}"
      loop_control:
        loop_var: current_app
        label: "{{ current_app }}"

  post_tasks:
    - name: Deployment complete summary
      ansible.builtin.debug:
        msg: |
          ========================================
          Deployment Complete
          ========================================
          Apps deployed: {{ apps_to_deploy | join(', ') }}
          Cloud: {{ cloud }}
          Environment: {{ env }}
          ========================================
