# .github/workflows/deploy-main.yml
name: 🚀 Deploy Landing Zone

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        type: choice
        options:
          - nonprod
          - prod
          - sandbox
          - all-environments
      component:
        description: 'Component to deploy'
        required: true
        type: choice
        options:
          - all
          - bootstrap-only
          - shared-infrastructure
          - teams-only
      action:
        description: 'Terraform action'
        required: true
        type: choice
        options:
          - plan
          - apply
          - destroy
      dry_run:
        description: 'Dry run mode (plan only)'
        required: false
        type: boolean
        default: true

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      environments: ${{ steps.matrix.outputs.environments }}
      deploy_bootstrap: ${{ steps.flags.outputs.bootstrap }}
    steps:
      - name: Set environment matrix
        id: matrix
        run: |
          if [[ "${{ inputs.environment }}" == "all-environments" ]]; then
            echo "environments=[\"nonprod\",\"sandbox\",\"prod\"]" >> $GITHUB_OUTPUT
          else
            echo "environments=[\"${{ inputs.environment }}\"]" >> $GITHUB_OUTPUT
          fi
          
      - name: Set component flags  
        id: flags
        run: |
          case "${{ inputs.component }}" in
            "all"|"bootstrap-only")
              echo "bootstrap=true" >> $GITHUB_OUTPUT
              ;;
            *)
              echo "bootstrap=false" >> $GITHUB_OUTPUT
              ;;
          esac

  # Bootstrap deployment using your tf_deploy.sh script
  deploy-bootstrap:
    needs: setup
    if: needs.setup.outputs.deploy_bootstrap == 'true'
    strategy:
      matrix:
        environment: ${{ fromJson(needs.setup.outputs.environments) }}
      fail-fast: false
      max-parallel: 1  # Deploy environments sequentially
    uses: ./.github/workflows/bootstrap-workflow.yml
    with:
      environment: ${{ matrix.environment }}
      action: ${{ inputs.action }}
      dry_run: ${{ inputs.dry_run }}
    secrets: inherit

  summary:
    needs: [setup, deploy-bootstrap]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Final Summary
        run: |
          echo "## 🎯 Deployment Complete" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Component:** ${{ inputs.component }}" >> $GITHUB_STEP_SUMMARY
          echo "**Environment(s):** ${{ inputs.environment }}" >> $GITHUB_STEP_SUMMARY
          echo "**Action:** ${{ inputs.action }}" >> $GITHUB_STEP_SUMMARY
          echo "**Bootstrap Result:** ${{ needs.deploy-bootstrap.result }}" >> $GITHUB_STEP_SUMMARY
