---
- name: GitHub Enterprise Server Upgrade Workflow
  hosts: localhost
  gather_facts: no
  
  tasks:
    - name: Validate inventory and variables
      assert:
        that:
          - groups['github_enterprise'] is defined
          - upgrade_package is defined
        fail_msg: "Missing required inventory group 'github_enterprise' or upgrade_package variable"

    - name: Display upgrade plan
      debug:
        msg: |
          GitHub Enterprise Server Upgrade Plan:
          - Target servers: {{ groups['github_enterprise'] | join(', ') }}
          - Package: {{ upgrade_package }}
          - Environment: {{ env | default('production') }}
          - Backup verification: {{ verify_backup | default(true) }}

- name: "Phase 1: Preflight Checks"
  hosts: github_enterprise
  gather_facts: yes

  pre_tasks:
    - name: Set phase tracking
      set_fact:
        current_phase: "preflight"
        upgrade_start_time: "{{ ansible_date_time.iso8601 }}"

  roles:
    - role: github_enterprise/ghe_preflight
      tags: 
        - preflight
        - safety_checks

  post_tasks:
    - name: Log preflight completion
      lineinfile:
        path: "{{ log_file_path }}/ghes_upgrade.log"
        line: "{{ ansible_date_time.iso8601 }}: Phase 1 (Preflight) completed successfully"
        create: yes
      delegate_to: localhost

- name: "Phase 2: Pre-upgrade Preparation"
  hosts: github_enterprise
  gather_facts: no
  
  pre_tasks:
    - name: Set phase tracking
      set_fact:
        current_phase: "pre_upgrade"

  roles:
    - role: github_enterprise/ghe_maintenance
      tags:
        - maintenance_mode
        - preparation

  post_tasks:
    - name: Log pre-upgrade completion
      lineinfile:
        path: "{{ log_file_path }}/ghes_upgrade.log"
        line: "{{ ansible_date_time.iso8601 }}: Phase 2 (Pre-upgrade) completed successfully"
        create: yes
      delegate_to: localhost

- name: "Phase 3: Execute Upgrade"
  hosts: github_enterprise
  gather_facts: no
  
  pre_tasks:
    - name: Set phase tracking
      set_fact:
        current_phase: "upgrade_execution"

  roles:
    - role: github_enterprise/ghe_upgrade
      tags:
        - upgrade
        - reboot

  post_tasks:
    - name: Log upgrade execution
      lineinfile:
        path: "{{ log_file_path }}/ghes_upgrade.log"
        line: "{{ ansible_date_time.iso8601 }}: Phase 3 (Upgrade execution) initiated"
        create: yes
      delegate_to: localhost

- name: "Phase 4: Post-upgrade Monitoring"
  hosts: github_enterprise
  gather_facts: yes
  
  pre_tasks:
    - name: Set phase tracking
      set_fact:
        current_phase: "post_upgrade_monitoring"

  roles:
    - role: github_enterprise/ghe_monitoring
      tags:
        - monitoring
        - validation

  post_tasks:
    - name: Log completion
      lineinfile:
        path: "{{ log_file_path }}/ghes_upgrade.log"
        line: "{{ ansible_date_time.iso8601 }}: Phase 4 (Post-upgrade) completed - Upgrade successful!"
        create: yes
      delegate_to: localhost
