name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to destroy'
        required: true
        default: 'nonprod'
        type: choice
        options:
          - nonprod
          - prod
      confirm_destroy:
        description: 'Type the environment name followed by "DESTROY" to confirm (e.g., "nonprod DESTROY")'
        required: true
        type: string

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  terraform-destroy:
    # Only run if confirmation matches "{environment} DESTROY"
    if: github.event.inputs.confirm_destroy == format('{0} DESTROY', github.event.inputs.environment)
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    defaults:
      run:
        working-directory: terraform
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Azure Login with OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.0"
      
      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="resource_group_name=${{ secrets.TFSTATE_RESOURCE_GROUP }}" \
            -backend-config="storage_account_name=${{ secrets.TFSTATE_STORAGE_ACCOUNT }}" \
            -backend-config="container_name=${{ secrets.TFSTATE_CONTAINER }}" \
            -backend-config="key=${{ github.event.inputs.environment }}.tfstate" \
            -backend-config="environment=usgovernment"
      
      - name: Setup Terraform Workspace
        run: |
          terraform workspace select ${{ github.event.inputs.environment }}
      
      - name: Terraform Plan Destroy
        run: |
          terraform plan \
            -destroy \
            -var-file="environments/${{ github.event.inputs.environment }}.tfvars" \
            -var="ssh_public_key=${{ secrets.SSH_PUBLIC_KEY }}" \
            -out=tfplan-destroy
      
      - name: Terraform Destroy
        run: terraform apply -auto-approve tfplan-destroy
      
      - name: Cleanup Terraform workspace
        if: success()
        run: |
          terraform workspace select default
          terraform workspace delete ${{ github.event.inputs.environment }}
        continue-on-error: true
