---
- name: Get current GitHub Enterprise version
  command: ghe-version
  register: ghe_version_output
  changed_when: false

- name: Set current version fact
  set_fact:
    current_ghes_version: "{{ ghe_version_output.stdout | trim }}"

- name: Verify upgrade path is valid (cannot skip more than one feature release)
  assert:
    that:
      - current_version.split('.')[0] | int == target_version.split('.')[0] | int or
        current_version.split('.')[0] | int == target_version.split('.')[0] | int - 1 or
        (current_version.split('.')[0] | int == target_version.split('.')[0] | int and
         current_version.split('.')[1] | int == target_version.split('.')[1] | int - 1) or
        (current_version.split('.')[0] | int == target_version.split('.')[0] | int and
         current_version.split('.')[1] | int == target_version.split('.')[1] | int) or
        (current_version.split('.')[0] | int == target_version.split('.')[0] | int - 1 and
         current_version.split('.')[1] | int == 11 and
         target_version.split('.')[1] | int == 13)
    fail_msg: "Cannot upgrade from {{ current_version }} to {{ target_version }}. The upgrade path is not supported."
    success_msg: "Upgrade path from {{ current_version }} to {{ target_version }} is valid."
