name: Deploy Application

on:
  push:
    branches: [main]
    paths:
      - 'charts/**'
      - 'values/**'
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        type: choice
        options:
          - upgrade
          - install
          - uninstall
          - diff
          - template
        default: upgrade
      environment:
        description: 'Target environment'
        required: true
        type: choice
        options:
          - staging
          - prod-east
          - prod-west
        default: staging
      dry-run:
        description: 'Dry run only'
        required: false
        type: boolean
        default: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'staging' }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy Wiz Connector
        uses: ./.github/actions/helm-deploy
        with:
          action: ${{ github.event.inputs.action || 'upgrade' }}
          kubeconfig: ${{ secrets.KUBECONFIG }}
          cluster-name: ${{ github.event.inputs.environment || 'staging' }}
          
          # Prerequisites
          prereq-enabled: 'true'
          prereq-repo-name: platform
          prereq-repo-url: https://your-org.github.io/platform-helm-charts
          prereq-chart: platform/platform-prereqs
          prereq-version: '1.0.0'
          prereq-values-files: values/prereqs-${{ github.event.inputs.environment || 'staging' }}.yaml
          
          # Application
          release-name: wiz-connector
          namespace: wiz
          chart: ./charts/wiz-connector
          values-files: values/app-${{ github.event.inputs.environment || 'staging' }}.yaml
          
          # Options
          atomic: 'true'
          wait: 'true'
          timeout: '10m'
          dry-run: ${{ github.event.inputs.dry-run || 'false' }}
          verify-install: 'true'
          required-resources: 'deployment/wiz-connector,secret/wiz-api-credentials'
          
          # Notifications
          slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
