---
- name: Validate inputs
  ansible.builtin.include_tasks: preflight.yml
  tags: ['always']

- name: "Narrow the instance list to: {{ _ghr_only_ids | join(', ') }}"
  ansible.builtin.set_fact:
    github_runner_instances: "{{ github_runner_instances | selectattr('id', 'in', _ghr_only_ids) | list }}"
  when: _ghr_only_ids | length > 0
  tags: ['always']

- name: "Dispatch action: {{ github_runner_action }}"
  ansible.builtin.include_tasks: "{{ github_runner_action }}.yml"
  tags: ['always']
