{{- if .Values.secretProviderClass.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.secretProviderClass.name | default (include "platform-prereqs.fullname" .) }}
  namespace: {{ include "platform-prereqs.namespace" . }}
  labels:
    {{- include "platform-prereqs.labels" . | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations:
    {{- include "platform-prereqs.annotations" . | nindent 4 }}
  {{- end }}
spec:
  provider: {{ .Values.secretProviderClass.provider }}
  
  parameters:
    {{- if eq .Values.secretProviderClass.provider "azure" }}
    usePodIdentity: "{{ .Values.secretProviderClass.azure.usePodIdentity }}"
    useVMManagedIdentity: "{{ .Values.secretProviderClass.azure.useVMManagedIdentity }}"
    clientID: {{ .Values.secretProviderClass.azure.clientId | quote }}
    keyvaultName: {{ .Values.secretProviderClass.azure.keyvaultName | quote }}
    tenantId: {{ .Values.secretProviderClass.azure.tenantId | quote }}
    objects: |
      array:
        {{- range .Values.secretProviderClass.azure.secrets }}
        - |
          objectName: {{ .name }}
          objectType: {{ .objectType | default "secret" }}
          {{- if .alias }}
          objectAlias: {{ .alias }}
          {{- end }}
          {{- if .objectVersion }}
          objectVersion: {{ .objectVersion }}
          {{- end }}
        {{- end }}
        {{- range .Values.secretProviderClass.azure.keys }}
        - |
          objectName: {{ .name }}
          objectType: key
          {{- if .alias }}
          objectAlias: {{ .alias }}
          {{- end }}
        {{- end }}
        {{- range .Values.secretProviderClass.azure.certificates }}
        - |
          objectName: {{ .name }}
          objectType: cert
          {{- if .alias }}
          objectAlias: {{ .alias }}
          {{- end }}
        {{- end }}
    {{- end }}

    {{- if eq .Values.secretProviderClass.provider "aws" }}
    region: {{ .Values.secretProviderClass.aws.region | quote }}
    objects: |
      {{- range .Values.secretProviderClass.aws.secrets }}
      - objectName: {{ .arn | quote }}
        objectType: secretsmanager
        {{- if .alias }}
        objectAlias: {{ .alias }}
        {{- end }}
        {{- if .jmesPath }}
        jmesPath:
          {{- range .jmesPath }}
          - path: {{ .path }}
            objectAlias: {{ .objectAlias }}
          {{- end }}
        {{- end }}
      {{- end }}
    {{- end }}

    {{- if eq .Values.secretProviderClass.provider "vault" }}
    vaultAddress: {{ .Values.secretProviderClass.vault.address | quote }}
    roleName: {{ .Values.secretProviderClass.vault.roleName | quote }}
    objects: |
      {{- range .Values.secretProviderClass.vault.secrets }}
      - objectName: {{ .name | quote }}
        secretPath: {{ .path | quote }}
        secretKey: {{ .key | default .name | quote }}
      {{- end }}
    {{- end }}

  {{- if .Values.secretProviderClass.syncSecret.enabled }}
  secretObjects:
    - secretName: {{ .Values.secretProviderClass.syncSecret.secretName }}
      type: {{ .Values.secretProviderClass.syncSecret.type | default "Opaque" }}
      data:
        {{- range .Values.secretProviderClass.syncSecret.data }}
        - objectName: {{ .objectName }}
          key: {{ .key }}
        {{- end }}
  {{- end }}
{{- end }}
