name: Build Password Manager

on:
  release:
    types: [ created ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            output_name: passwordmanager-linux
          - os: windows-latest
            output_name: passwordmanager-windows.exe
          - os: macos-latest
            output_name: passwordmanager-macos

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.2'
        check-latest: true

    - name: Get dependencies
      working-directory: ./Go
      run: go mod download

    - name: Build
      working-directory: ./Go
      run: go build -v -o ../${{ matrix.output_name }}

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.output_name }}
        path: ${{ matrix.output_name }}
        
    # Optional: Create release artifacts when triggered by a release
    - name: Upload to release
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v2
      with:
        files: ${{ matrix.output_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
